=== Seekatar/OktaPosh/OktaPosh/public/configuration-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "http://oktaposhconifguration",
    "title": "OktaPoshConfiguration Schema",
    "type": "object",
    "required": [
        "authorizationServer"
    ],
    "properties": {
        "authorizationServer": {
            "description": "The authorization server to add or update",
            "$ref": "#/$defs/authorizationServer"
        },
        "groups": {
            "description": "The list of groups to add",
            "type": "array",
            "items": {
                "$ref": "#/$defs/group"
            }
        },
        "serverApplications": {
            "description": "Server-type applications",
            "type": "array",
            "items": {
                "$ref": "#/$defs/serverApplication"
            }
        },
        "spaApplications": {
            "description": "SPA-type applications",
            "type": "array",
            "items": {
                "$ref": "#/$defs/spaApplication"
            }
        },
        "variables": {
            "description": "Variables to substitute in the file.",
            "type": "array",
            "items": {
                "$ref": "#/$defs/variable"
            }
        }
    },
    "$defs": {
        "authorizationServer": {
            "required": [
                "name"
            ],
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the AuthorizationServer",
                    "type": "string"
                },
                "description": {
                    "description": "Optional description",
                    "type": "string",
                    "default": "added by OktaPosh"
                },
                "audiences": {
                    "description": "Audience value for the AuthorizationServer",
                    "type": "string"
                },
                "scopes": {
                    "description": "Array of scopes to add to the AuthorizationServer",
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/scope"
                    }
                },
                "claims": {
                    "description": "Array of claims to add to the AuthorizationServer",
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/claim"
                    }
                }
            }
        },
        "claim": {
            "type": "object",
            "required": [
                "name",
                "valueType",
                "value"
            ],
            "properties": {
                "name": {
                    "description": "test",
                    "type": "string"
                },
                "valueType": {
                    "description": "test",
                    "enum": [
                        "EXPRESSION",
                        "GROUPS"
                    ]
                },
                "claimType": {
                    "description": "test",
                    "enum": [
                        "RESOURCE",
                        "IDENTITY",
                        "ACCESS_TOKEN",
                        "ID_TOKEN"
                    ]
                },
                "value": {
                    "description": "test",
                    "type": "string"
                },
                "groupFilterType": {
                    "description": "test",
                    "enum": [
                        "STARTS_WITH",
                        "EQUALS",
                        "CONTAINS",
                        "REGEX",
                        ""
                    ]
                },
                "scopes": {
                    "description": "test",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "alwaysIncludeInToken": {
                    "description": "test",
                    "type": "boolean"
                },
                "inactive": {
                    "description": "test",
                    "type": "boolean"
                }
            }
        },
        "group": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Name of the Okta Group",
                    "type": "string"
                },
                "description": {
                    "description": "Optional description",
                    "type": "string"
                },
                "scope": {
                    "description": "Set to also add a claim and scope",
                    "type": "string"
                }
            }
        },
        "serverApplication": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "test",
                    "type": "string"
                },
                "signOnMode": {
                    "description": "test",
                    "type": "string"
                },
                "scopes": {
                    "description": "test",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "inactive": {
                    "description": "test",
                    "type": "boolean"
                },
                "properties": {
                    "description": "Additional properties for the app",
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "spaApplication": {
            "type": "object",
            "required": [
                "name",
                "loginUri",
                "redirectUris",
                "grantTypes"
            ],
            "properties": {
                "name": {
                    "description": "test",
                    "type": "string"
                },
                "redirectUris": {
                    "description": "test",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1
                },
                "loginUri": {
                    "description": "test",
                    "type": "string"
                },
                "postLogoutUris": {
                    "description": "test",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "origins": {
                    "description": "test",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "grantTypes": {
                    "description": "test",
                    "type": "array",
                    "items": {
                        "enum": [
                            "implicit",
                            "code",
                            "refresh",
                            "authorization_code",
                            "refresh_token"
                        ]
                    },
                    "minItems": 1
                },
                "scopes": {
                    "description": "test",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "inactive": {
                    "description": "test",
                    "type": "boolean"
                }
            }
        },
        "scope": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Name of Okta Scope",
                    "type": "string"
                },
                "description": {
                    "description": "Optional description",
                    "type": "string"
                },
                "metadataPublish": {
                    "description": "Set to publish in public metadata",
                    "type": "boolean"
                },
                "isDefault": {
                    "description": "Set to include in the default scope",
                    "type": "boolean"
                }
            }
        },
        "variable": {
            "type": "object",
            "required": [
                "name",
                "value"
            ],
            "properties": {
                "name": {
                    "description": "Name of the {{ variable }}",
                    "type": "string"
                },
                "value": {
                    "description": "Value of the variable",
                    "type": "string"
                }
            }
        }
    }
}

=== Seekatar/OktaPosh/OktaPosh/public/datacapture-ui.json
{
    "$schema": "./configuration-schema.json",
    "variables": [
        {
            "name": "ui-path",
            "value": "dc-ui"
        }
    ],
    "authorizationServer": {
        "name": "Casualty-DataCapture-AS",
        "audience": "api://cccis/reliance/{{ ui-path }}",
        "scopes": [],
        "claims": [
            {
                "name": "email",
                "valueType": "EXPRESSION",
                "claimType": "ACCESS_TOKEN",
                "value": "user.email"
            },
            {
                "name": "friendlyName",
                "valueType": "EXPRESSION",
                "value": "String.len(user.displayName) > 0 ? user.displayName : user.firstName+ \" \" + user.lastName",
                "claimType": "ACCESS_TOKEN"
            },
            {
                "name": "friendlyName",
                "valueType": "EXPRESSION",
                "value": "String.len(user.displayName) > 0 ? user.displayName : user.firstName+ \" \" + user.lastName",
                "claimType": "ID_TOKEN"
            },
            {
                "name": "login",
                "valueType": "EXPRESSION",
                "value": "user.email",
                "claimType": "ACCESS_TOKEN"
            }
        ]
    },
    "groups": [
        {
            "name": "CCC-DataCapture-Client-den1-Group",
            "createScope": true
        },
        {
            "name": "CCC-DataCapture-Client-nw-Group",
            "createScope": true
        },
        {
            "name": "CCC-DataCapture-Client-safeco-Group",
            "createScope": true
        },
        {
            "name": "CCC-DataCapture-Client-geico-Group",
            "createScope": true
        },
        {
            "name": "CCC-DataCapture-Client-usaa-Group",
            "createScope": true
        }
    ],
    "spaApplications": [
        {
            "loginUri": "https://rbr{{ domainSuffix }}.{{ Cluster }}.aws.casualty.cccis.com/{{ ui-path }}",
            "redirectUris": [
                "https://rbr{{ domainSuffix }}.{{ cluster }}.aws.casualty.cccis.com/{{ ui-path }}/implicit/callback"
            ],
            "postLogoutUris": [
                "https://rbr{{ domainSuffix }}.{{ Cluster }}.aws.casualty.cccis.com/{{ ui-path }}"
            ],
            "origins": [
                "https://rbr{{ domainSuffix }}.{{ Cluster }}.aws.casualty.cccis.com"
            ],
            "grantTypes": [
                "implicit",
                "authorization_code"
            ],
            "name": "CCC-CASReliance-DataCapture",
            "policyName": "CCC-CASReliance-DataCapture-Policy",
            "scopes": [
                "*"
            ]
        }
    ]
}

=== Seekatar/OktaPosh/tests/samples/import/ui-app.json
{
    "$schema": "../../../schemas/configuration-schema.json",
    "variables": [
        {
            "name": "ui-path",
            "value": "dc-ui"
        },
        {
            "name": "additionalRedirect",
            "value": ""
        },
        {
            "name": "additionalLogout",
            "value": ""
        },
        {
            "name": "additionalOrigins",
            "value": ""
        }
    ],
    "authorizationServer": {
        "name": "Casualty-DataCapture-AS",
        "description": "DataCapture UI for casualty",
        "audience": "https://reliance/{{ ui-path }}",
        "scopes": [],
        "claims": [
            {
                "name": "email",
                "valueType": "EXPRESSION",
                "claimType": "ACCESS_TOKEN",
                "value": "user.email"
            },
            {
                "name": "friendlyName",
                "valueType": "EXPRESSION",
                "value": "String.len(user.displayName) > 0 ? user.displayName : user.firstName+ \" \" + user.lastName",
                "claimType": "ACCESS_TOKEN"
            },
            {
                "name": "friendlyName",
                "valueType": "EXPRESSION",
                "value": "String.len(user.displayName) > 0 ? user.displayName : user.firstName+ \" \" + user.lastName",
                "claimType": "ID_TOKEN"
            },
            {
                "name": "login",
                "valueType": "EXPRESSION",
                "value": "user.email",
                "claimType": "ACCESS_TOKEN"
            }
        ]
    },
    "groups": [
        {
            "name": "CCC-DataCapture-Client-den1-Group",
            "scope": "casualty.datacapture.client.den1"
        },
        {
            "name": "CCC-DataCapture-Client-nw-Group",
            "scope": "casualty.datacapture.client.nw"
        },
        {
            "name": "CCC-DataCapture-Client-safeco-Group",
            "scope": "casualty.datacapture.client.safeco"
        },
        {
            "name": "CCC-DataCapture-Client-geico-Group",
            "scope": "casualty.DataCapture.client.geico"
        },
        {
            "name": "CCC-DataCapture-Client-usaa-Group",
            "scope": "casualty.datacapture.client.usaa"
        }
    ],
    "spaApplications": [
        {
            "name": "CCC-CASDataCapture-SPA",
            "policyName": "CCC-CASDataCapture-SPA-Policy",
            "loginUri": "https://rbr{{ domainSuffix }}.{{ cluster }}.aws.casualty.cccis.com/{{ ui-path }}",
            "redirectUris": [
                "https://rbr{{ domainSuffix }}.casualty.mycccportal.com/{{ ui-path }}/implicit/callback",
                "https://rbr{{ domainSuffix }}.{{ cluster }}.aws.casualty.cccis.com/{{ ui-path }}/implicit/callback"
                ,"{{ additionalRedirect }}"
            ],
            "postLogoutUris": [
                "https://rbr{{ domainSuffix }}.casualty.mycccportal.com/{{ ui-path }}",
                "https://rbr{{ domainSuffix }}.{{ cluster }}.aws.casualty.cccis.com/{{ ui-path }}"
                ,"{{ additionalLogout }}"
            ],
            "origins": [
                "https://rbr{{ domainSuffix }}.{{ cluster }}.aws.casualty.cccis.com"
                ,"{{ additionalOrigins }}"
            ],
            "grantTypes": [
                "implicit",
                "authorization_code"
            ],
            "scopes": [
                "*"
            ],
            "groups": [
                "CCC-DataCapture-Client-USAA-Group",
                "CCC-DataCapture-Client-SAFECO-Group",
                "CCC-DataCapture-Client-NW-Group",
                "CCC-DataCapture-Client-geico-Group",
                "CCC-DataCapture-Client-DEN1-Group"
            ]
        }
    ]
}
